version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: my-laravel-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
    webserver:
        image: nginx:alpine
        container_name: my-laravel-webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - app-network
    db:
        image: mysql:5.7
        container_name: my-laravel-db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
