version: "3.8"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: boarder-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./database:/var/www/database
        networks:
            - app-network
    webserver:
        image: nginx:alpine
        container_name: boarder-webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx:/etc/nginx/conf.d/
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
